// 사자성어 데이터 (25개)
// 7급 이상(100자+) 학습 후 해금
// 각 사자성어는 8급·7급·6급에서 학습한 한자들로 구성

export interface IdiomChar {
  hanja: string;
  sound: string;
  meaning: string;
}

export interface Idiom {
  id: string;
  hanja: string;           // "一石二鳥"
  korean: string;          // "일석이조"
  meaning: string;         // "돌 하나로 새 두 마리"
  explanation: string;     // 한 줄 뜻 풀이
  story: string;           // 유래/사용 맥락 (2~3문장)
  example: string;         // 예문 (Korean 문장)
  chars: IdiomChar[];      // 각 한자 분해
  level: "beginner" | "intermediate" | "advanced"; // 난이도
  unlock_at: number;       // 몇 자 학습 후 해금
}

export const IDIOMS: Idiom[] = [
  {
    id: "일석이조",
    hanja: "一石二鳥",
    korean: "일석이조",
    meaning: "하나의 돌로 두 마리 새를 잡는다",
    explanation: "한 가지 일로 두 가지 이익을 얻음",
    story: "영어 'kill two birds with one stone'과 같은 뜻입니다. 한 번의 노력으로 두 가지 목표를 동시에 달성할 때 사용합니다.",
    example: "운동을 하면서 친구도 사귀니 일석이조네요.",
    chars: [
      { hanja: "一", sound: "일", meaning: "하나" },
      { hanja: "石", sound: "석", meaning: "돌" },
      { hanja: "二", sound: "이", meaning: "둘" },
      { hanja: "鳥", sound: "조", meaning: "새" },
    ],
    level: "beginner",
    unlock_at: 100,
  },
  {
    id: "백문불여일견",
    hanja: "百聞不如一見",
    korean: "백문불여일견",
    meaning: "백 번 듣는 것이 한 번 보는 것만 못하다",
    explanation: "직접 경험하는 것이 간접 정보보다 훨씬 낫다",
    story: "중국 한서(漢書)에서 유래한 표현입니다. 아무리 많이 들어도 실제로 눈으로 확인하는 것보다 확실한 것은 없다는 의미입니다.",
    example: "백문불여일견이라고, 직접 가서 확인해보는 게 좋겠어.",
    chars: [
      { hanja: "百", sound: "백", meaning: "백" },
      { hanja: "聞", sound: "문", meaning: "들을" },
      { hanja: "不", sound: "불", meaning: "아닐" },
      { hanja: "如", sound: "여", meaning: "같을" },
      { hanja: "一", sound: "일", meaning: "하나" },
      { hanja: "見", sound: "견", meaning: "볼" },
    ],
    level: "intermediate",
    unlock_at: 230,
  },
  {
    id: "사면초가",
    hanja: "四面楚歌",
    korean: "사면초가",
    meaning: "사방이 초나라 노래",
    explanation: "사방이 모두 적에게 둘러싸여 어디에도 도움을 받을 수 없는 상황",
    story: "초한지(楚漢志)에서 유래했습니다. 항우가 유방의 군대에 포위되었을 때 사방에서 초나라 노래가 들려와 군심이 무너졌다는 고사에서 왔습니다.",
    example: "협상이 모두 결렬되어 우리 회사는 사면초가에 놓였다.",
    chars: [
      { hanja: "四", sound: "사", meaning: "넷" },
      { hanja: "面", sound: "면", meaning: "낯" },
      { hanja: "楚", sound: "초", meaning: "초나라" },
      { hanja: "歌", sound: "가", meaning: "노래" },
    ],
    level: "intermediate",
    unlock_at: 240,
  },
  {
    id: "온고지신",
    hanja: "溫故知新",
    korean: "온고지신",
    meaning: "옛것을 익히고 새것을 안다",
    explanation: "과거의 지식을 바탕으로 새로운 것을 배우고 깨닫는다",
    story: "논어(論語)의 공자 말씀에서 유래했습니다. 스승이 될 자격은 옛 것을 깊이 이해하면서 동시에 새로운 것을 배울 수 있는 사람이라고 했습니다.",
    example: "온고지신의 자세로 역사를 공부하면 현재를 더 잘 이해할 수 있다.",
    chars: [
      { hanja: "溫", sound: "온", meaning: "따뜻할" },
      { hanja: "故", sound: "고", meaning: "옛" },
      { hanja: "知", sound: "지", meaning: "알" },
      { hanja: "新", sound: "신", meaning: "새" },
    ],
    level: "intermediate",
    unlock_at: 220,
  },
  {
    id: "유비무환",
    hanja: "有備無患",
    korean: "유비무환",
    meaning: "준비가 있으면 근심이 없다",
    explanation: "미리 잘 준비해 두면 걱정할 것이 없다",
    story: "서경(書經)에 실린 말로, 평소에 철저히 대비하면 예상치 못한 상황이 와도 위기를 피할 수 있다는 교훈을 담고 있습니다.",
    example: "유비무환의 정신으로 비상 식량을 준비해 두었다.",
    chars: [
      { hanja: "有", sound: "유", meaning: "있을" },
      { hanja: "備", sound: "비", meaning: "갖출" },
      { hanja: "無", sound: "무", meaning: "없을" },
      { hanja: "患", sound: "환", meaning: "근심" },
    ],
    level: "beginner",
    unlock_at: 110,
  },
  {
    id: "청출어람",
    hanja: "靑出於藍",
    korean: "청출어람",
    meaning: "푸른색은 쪽에서 나왔지만 쪽보다 더 푸르다",
    explanation: "제자가 스승보다 더 뛰어나게 됨",
    story: "순자(荀子)에서 유래한 표현입니다. 원래 학문의 중요성을 말하는 맥락이었지만, 후에 제자가 스승을 능가할 때 쓰는 말이 되었습니다.",
    example: "그 제자는 청출어람으로 스승보다 더 훌륭한 화가가 되었다.",
    chars: [
      { hanja: "靑", sound: "청", meaning: "푸를" },
      { hanja: "出", sound: "출", meaning: "날" },
      { hanja: "於", sound: "어", meaning: "에서" },
      { hanja: "藍", sound: "람", meaning: "쪽" },
    ],
    level: "advanced",
    unlock_at: 320,
  },
  {
    id: "이심전심",
    hanja: "以心傳心",
    korean: "이심전심",
    meaning: "마음으로 마음에 전한다",
    explanation: "말하지 않아도 서로의 마음이 통함",
    story: "불교 선종(禪宗)에서 유래한 말로, 스승이 제자에게 마음에서 마음으로 진리를 전달한다는 의미였습니다. 현재는 서로 말하지 않아도 통하는 상황에 사용합니다.",
    example: "오랜 친구 사이라 이심전심으로 서로의 뜻을 알았다.",
    chars: [
      { hanja: "以", sound: "이", meaning: "써" },
      { hanja: "心", sound: "심", meaning: "마음" },
      { hanja: "傳", sound: "전", meaning: "전할" },
      { hanja: "心", sound: "심", meaning: "마음" },
    ],
    level: "beginner",
    unlock_at: 170,
  },
  {
    id: "동문서답",
    hanja: "東問西答",
    korean: "동문서답",
    meaning: "동쪽을 물어보면 서쪽을 대답한다",
    explanation: "물음과 전혀 관계없는 엉뚱한 대답을 함",
    story: "질문의 요점을 전혀 파악하지 못하고 엉뚱한 대답을 하는 상황을 비유적으로 표현합니다. 요즘은 의도적으로 핵심을 피하는 경우에도 사용합니다.",
    example: "왜 늦었냐고 물었더니 동문서답으로 날씨 얘기만 했다.",
    chars: [
      { hanja: "東", sound: "동", meaning: "동녘" },
      { hanja: "問", sound: "문", meaning: "물을" },
      { hanja: "西", sound: "서", meaning: "서녘" },
      { hanja: "答", sound: "답", meaning: "대답" },
    ],
    level: "beginner",
    unlock_at: 140,
  },
  {
    id: "천고마비",
    hanja: "天高馬肥",
    korean: "천고마비",
    meaning: "하늘은 높고 말은 살찐다",
    explanation: "가을 하늘이 맑고 높으며 먹을 것이 풍성한 좋은 계절",
    story: "원래 중국에서 가을이 되면 북방 유목민족이 살찐 말을 타고 남침해 올 위험을 경계하는 말이었습니다. 현재 한국에서는 '풍요로운 가을'의 의미로 변화했습니다.",
    example: "천고마비의 계절, 가을 소풍을 가기 딱 좋은 날씨다.",
    chars: [
      { hanja: "天", sound: "천", meaning: "하늘" },
      { hanja: "高", sound: "고", meaning: "높을" },
      { hanja: "馬", sound: "마", meaning: "말" },
      { hanja: "肥", sound: "비", meaning: "살찔" },
    ],
    level: "beginner",
    unlock_at: 150,
  },
  {
    id: "설상가상",
    hanja: "雪上加霜",
    korean: "설상가상",
    meaning: "눈 위에 서리가 더해진다",
    explanation: "어려운 일이 겹치고 겹쳐 더욱 힘들어짐",
    story: "이미 힘든 상황에서 또 다른 불행이 겹칠 때 사용하는 표현입니다. 영어의 'adding insult to injury'와 비슷한 표현입니다.",
    example: "지갑을 잃어버리고 설상가상으로 핸드폰까지 고장났다.",
    chars: [
      { hanja: "雪", sound: "설", meaning: "눈" },
      { hanja: "上", sound: "상", meaning: "위" },
      { hanja: "加", sound: "가", meaning: "더할" },
      { hanja: "霜", sound: "상", meaning: "서리" },
    ],
    level: "beginner",
    unlock_at: 180,
  },
  {
    id: "자업자득",
    hanja: "自業自得",
    korean: "자업자득",
    meaning: "자기가 지은 일은 자기가 얻는다",
    explanation: "자기가 한 행동의 결과는 자기가 받는다",
    story: "불교의 업(業, karma) 사상에서 유래한 말입니다. 자기가 한 행동의 좋고 나쁜 결과는 반드시 자기에게 돌아온다는 인과응보의 원리를 표현합니다.",
    example: "공부를 안 했으니 시험을 망친 건 자업자득이야.",
    chars: [
      { hanja: "自", sound: "자", meaning: "스스로" },
      { hanja: "業", sound: "업", meaning: "업" },
      { hanja: "自", sound: "자", meaning: "스스로" },
      { hanja: "得", sound: "득", meaning: "얻을" },
    ],
    level: "beginner",
    unlock_at: 160,
  },
  {
    id: "조삼모사",
    hanja: "朝三暮四",
    korean: "조삼모사",
    meaning: "아침에 세 개, 저녁에 네 개",
    explanation: "눈앞의 차이에 속아 전체를 보지 못함, 또는 결과는 같지만 말로 속임",
    story: "중국 장자(莊子)에서 유래. 원숭이에게 도토리를 아침 3개 저녁 4개를 주자 화냈고, 아침 4개 저녁 3개라 하니 좋아했다는 이야기입니다.",
    example: "이름만 바꾸고 내용은 똑같으니, 조삼모사식 정책이네.",
    chars: [
      { hanja: "朝", sound: "조", meaning: "아침" },
      { hanja: "三", sound: "삼", meaning: "셋" },
      { hanja: "暮", sound: "모", meaning: "저녁" },
      { hanja: "四", sound: "사", meaning: "넷" },
    ],
    level: "intermediate",
    unlock_at: 270,
  },
  {
    id: "마이동풍",
    hanja: "馬耳東風",
    korean: "마이동풍",
    meaning: "말의 귀에 동풍",
    explanation: "남의 말을 전혀 귀담아 듣지 않음",
    story: "이백(李白)의 시에서 유래한 표현입니다. 봄바람이 말의 귀를 스쳐도 말은 전혀 신경 쓰지 않는다는 이미지에서, 남의 의견을 무시하는 태도를 비유합니다.",
    example: "아무리 충고해도 마이동풍이니 더는 말하기 싫다.",
    chars: [
      { hanja: "馬", sound: "마", meaning: "말" },
      { hanja: "耳", sound: "이", meaning: "귀" },
      { hanja: "東", sound: "동", meaning: "동녘" },
      { hanja: "風", sound: "풍", meaning: "바람" },
    ],
    level: "intermediate",
    unlock_at: 280,
  },
  {
    id: "오십보백보",
    hanja: "五十步百步",
    korean: "오십보백보",
    meaning: "오십 보와 백 보",
    explanation: "정도의 차이는 있지만 본질적으로는 서로 같음",
    story: "맹자(孟子)에서 유래. 전쟁에서 50보 도망친 병사가 100보 도망친 병사를 비웃었다는 고사에서 왔습니다. 차이는 있어도 잘못된 것은 마찬가지임을 뜻합니다.",
    example: "A당이나 B당이나 오십보백보라, 선택이 어렵다.",
    chars: [
      { hanja: "五", sound: "오", meaning: "다섯" },
      { hanja: "十", sound: "십", meaning: "열" },
      { hanja: "步", sound: "보", meaning: "걸음" },
      { hanja: "百", sound: "백", meaning: "백" },
      { hanja: "步", sound: "보", meaning: "걸음" },
    ],
    level: "intermediate",
    unlock_at: 290,
  },
  {
    id: "수수방관",
    hanja: "袖手傍觀",
    korean: "수수방관",
    meaning: "소매에 손을 넣고 옆에서 바라본다",
    explanation: "팔짱 끼고 보기만 할 뿐 도움을 주지 않음",
    story: "팔짱을 끼고(소매 속에 손을 넣고) 옆에서 구경만 한다는 뜻입니다. 도움이 필요한 상황에서 나 몰라라 하는 태도를 비판할 때 사용합니다.",
    example: "친구가 어려운데 수수방관하고 있을 수만은 없었다.",
    chars: [
      { hanja: "袖", sound: "수", meaning: "소매" },
      { hanja: "手", sound: "수", meaning: "손" },
      { hanja: "傍", sound: "방", meaning: "곁" },
      { hanja: "觀", sound: "관", meaning: "볼" },
    ],
    level: "advanced",
    unlock_at: 340,
  },
  {
    id: "구사일생",
    hanja: "九死一生",
    korean: "구사일생",
    meaning: "아홉 번 죽을 고비에서 한 번 살아남",
    explanation: "여러 차례의 위기를 간신히 넘기고 살아남음",
    story: "거의 확실한 죽음의 상황에서 기적적으로 살아남는 것을 표현합니다. 전쟁, 사고, 극한 상황에서 겨우 살아남았을 때 자주 사용합니다.",
    example: "산에서 조난되었지만 구사일생으로 구조되었다.",
    chars: [
      { hanja: "九", sound: "구", meaning: "아홉" },
      { hanja: "死", sound: "사", meaning: "죽을" },
      { hanja: "一", sound: "일", meaning: "하나" },
      { hanja: "生", sound: "생", meaning: "날" },
    ],
    level: "beginner",
    unlock_at: 130,
  },
  {
    id: "동병상련",
    hanja: "同病相憐",
    korean: "동병상련",
    meaning: "같은 병을 앓는 이들이 서로 불쌍히 여긴다",
    explanation: "같은 처지에 있는 사람들끼리 서로 동정하고 도움",
    story: "오월춘추(吳越春秋)에서 유래했습니다. 비슷한 고통이나 어려움을 겪고 있는 사람들이 서로의 처지를 이해하고 위로하는 상황에 씁니다.",
    example: "시험에 떨어진 우리는 동병상련의 심정으로 서로 위로했다.",
    chars: [
      { hanja: "同", sound: "동", meaning: "같을" },
      { hanja: "病", sound: "병", meaning: "병" },
      { hanja: "相", sound: "상", meaning: "서로" },
      { hanja: "憐", sound: "련", meaning: "불쌍히 여길" },
    ],
    level: "intermediate",
    unlock_at: 260,
  },
  {
    id: "일취월장",
    hanja: "日就月將",
    korean: "일취월장",
    meaning: "날마다 이루고 달마다 자란다",
    explanation: "날이 갈수록 점점 발전하고 성장함",
    story: "시경(詩經)에서 유래한 표현입니다. 꾸준한 노력으로 매일 매달 성장하는 모습을 긍정적으로 표현할 때 사용합니다.",
    example: "한자 공부를 시작한 후 어휘 실력이 일취월장하고 있다.",
    chars: [
      { hanja: "日", sound: "일", meaning: "날" },
      { hanja: "就", sound: "취", meaning: "이룰" },
      { hanja: "月", sound: "월", meaning: "달" },
      { hanja: "將", sound: "장", meaning: "나아갈" },
    ],
    level: "intermediate",
    unlock_at: 250,
  },
  {
    id: "전화위복",
    hanja: "轉禍爲福",
    korean: "전화위복",
    meaning: "재앙이 오히려 복으로 바뀐다",
    explanation: "어려운 상황이 계기가 되어 오히려 좋은 결과가 생김",
    story: "불행한 일이 뜻밖에 행운의 계기가 되는 경우에 씁니다. 위기를 기회로 바꾸는 긍정적 사고와도 연결됩니다.",
    example: "실직이 전화위복이 되어 더 좋은 직장을 얻었다.",
    chars: [
      { hanja: "轉", sound: "전", meaning: "구를" },
      { hanja: "禍", sound: "화", meaning: "재앙" },
      { hanja: "爲", sound: "위", meaning: "될" },
      { hanja: "福", sound: "복", meaning: "복" },
    ],
    level: "intermediate",
    unlock_at: 190,
  },
  {
    id: "어부지리",
    hanja: "漁父之利",
    korean: "어부지리",
    meaning: "어부의 이익",
    explanation: "둘이 싸우는 사이 엉뚱한 제3자가 이익을 차지함",
    story: "전국책(戰國策)에서 유래. 도요새와 조개가 서로 물고 싸우다가 어부에게 모두 잡혔다는 이야기에서 왔습니다. '방휼지쟁(蚌鷸之爭)'이라고도 합니다.",
    example: "두 후보가 서로 비방하다가 어부지리로 제3후보가 당선됐다.",
    chars: [
      { hanja: "漁", sound: "어", meaning: "고기 잡을" },
      { hanja: "父", sound: "부", meaning: "아비" },
      { hanja: "之", sound: "지", meaning: "의" },
      { hanja: "利", sound: "리", meaning: "이로울" },
    ],
    level: "advanced",
    unlock_at: 360,
  },
  {
    id: "과유불급",
    hanja: "過猶不及",
    korean: "과유불급",
    meaning: "지나침은 미치지 못함과 같다",
    explanation: "무엇이든 지나치면 모자란 것과 마찬가지로 좋지 않다",
    story: "논어(論語)에서 공자가 한 말입니다. 어떤 일이든 적절한 중용(中庸)이 중요하며, 너무 많거나 너무 적은 것은 모두 바람직하지 않다는 가르침입니다.",
    example: "과유불급이라고, 운동도 너무 무리하면 오히려 몸에 해롭다.",
    chars: [
      { hanja: "過", sound: "과", meaning: "지날" },
      { hanja: "猶", sound: "유", meaning: "오히려" },
      { hanja: "不", sound: "불", meaning: "아닐" },
      { hanja: "及", sound: "급", meaning: "미칠" },
    ],
    level: "intermediate",
    unlock_at: 300,
  },
  {
    id: "고진감래",
    hanja: "苦盡甘來",
    korean: "고진감래",
    meaning: "쓴 것이 다하면 단 것이 온다",
    explanation: "고생 끝에 즐거움이 온다",
    story: "힘든 시간을 참고 견디면 반드시 좋은 일이 찾아온다는 희망의 메시지를 담고 있습니다. 어려운 상황을 극복한 사람을 격려할 때 자주 사용합니다.",
    example: "3년간 고생한 끝에 합격하다니, 고진감래를 몸소 보여줬네.",
    chars: [
      { hanja: "苦", sound: "고", meaning: "쓸" },
      { hanja: "盡", sound: "진", meaning: "다할" },
      { hanja: "甘", sound: "감", meaning: "달" },
      { hanja: "來", sound: "래", meaning: "올" },
    ],
    level: "beginner",
    unlock_at: 120,
  },
  {
    id: "대기만성",
    hanja: "大器晩成",
    korean: "대기만성",
    meaning: "큰 그릇은 늦게 이루어진다",
    explanation: "크게 될 사람은 늦게 성공한다",
    story: "노자(老子)에서 유래한 표현입니다. 큰 종은 오랜 시간을 들여 만들어지듯, 진정으로 크게 될 사람은 오랜 노력과 시간이 필요하다는 의미입니다.",
    example: "나이 50에 성공한 그는 대기만성의 좋은 예다.",
    chars: [
      { hanja: "大", sound: "대", meaning: "클" },
      { hanja: "器", sound: "기", meaning: "그릇" },
      { hanja: "晩", sound: "만", meaning: "늦을" },
      { hanja: "成", sound: "성", meaning: "이룰" },
    ],
    level: "beginner",
    unlock_at: 200,
  },
  {
    id: "형설지공",
    hanja: "螢雪之功",
    korean: "형설지공",
    meaning: "반딧불과 눈빛으로 공부한 공",
    explanation: "어려운 환경에서도 고생하며 공부한 성과",
    story: "중국의 차윤은 반딧불을 모아 책을 읽고, 손강은 눈빛으로 책을 읽어 학문을 이루었다는 고사에서 왔습니다. 가난을 극복하고 이룬 학문적 성취를 칭찬할 때 씁니다.",
    example: "형설지공으로 쌓은 지식은 절대 잊히지 않는다.",
    chars: [
      { hanja: "螢", sound: "형", meaning: "반딧불" },
      { hanja: "雪", sound: "설", meaning: "눈" },
      { hanja: "之", sound: "지", meaning: "의" },
      { hanja: "功", sound: "공", meaning: "공" },
    ],
    level: "advanced",
    unlock_at: 380,
  },
  {
    id: "용두사미",
    hanja: "龍頭蛇尾",
    korean: "용두사미",
    meaning: "용의 머리에 뱀의 꼬리",
    explanation: "시작은 거창하지만 끝이 흐지부지함",
    story: "처음에는 용처럼 위풍당당하게 시작했으나 갈수록 뱀의 꼬리처럼 허술해진다는 뜻입니다. 시작과 끝의 차이가 큰 사람이나 일을 비판할 때 씁니다.",
    example: "처음엔 의욕적이었는데 용두사미로 끝나고 말았다.",
    chars: [
      { hanja: "龍", sound: "용", meaning: "용" },
      { hanja: "頭", sound: "두", meaning: "머리" },
      { hanja: "蛇", sound: "사", meaning: "뱀" },
      { hanja: "尾", sound: "미", meaning: "꼬리" },
    ],
    level: "beginner",
    unlock_at: 210,
  },
];

// 최소 학습 요건 확인 (7급 완료 기준: 100자 이상)
export const IDIOMS_MIN_LEARNED = 100;

export function getIdiomsByLevel(level: "beginner" | "intermediate" | "advanced"): Idiom[] {
  return IDIOMS.filter((idiom) => idiom.level === level);
}

export function getIdiomByChars(chars: string): Idiom | undefined {
  return IDIOMS.find((idiom) => idiom.chars === chars);
}

export function getAllIdioms(): Idiom[] {
  return IDIOMS;
}